[package]
name = "pento_rust"
version = "0.1.0"
authors = ["Sebastien <sebastien@migniot.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.2"
